## 花式索引(Fancy indexing)

花式索引：同时索引多个元素

In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1, 100, 10)
arr

array([ 4,  6, 25, 59,  8, 27, 81, 69, 91, 58])

同时取第二号，第四号，第六号元素

In [4]:
arr[[2,4,6]]  # 直接传递一个包含索引号的列表

array([25,  8, 81])

花式索引也适用于多维数组

In [8]:
M = arr.reshape(5,2)
M

array([[ 4,  6],
       [25, 59],
       [ 8, 27],
       [81, 69],
       [91, 58]])

In [10]:
# 提供(row,col)的组合
idx_row = [2, 4]
idx_col = [0, 1]

M[idx_row, idx_col]  # 索引坐标为(2,0),(4,1)的两个元素

array([ 8, 58])

借助花式索引可快速修改原数组的元素

In [12]:
print(arr)

# 将索引号为偶数的元素全部修改为99
idx = np.arange(0, len(arr), 2)
arr[idx] = 99

print(arr)

[ 4  6 25 59  8 27 81 69 91 58]
[99  6 99 59 99 27 99 69 99 58]
